import pandas as pd
import matplotlib.pyplot as plt
import koreanize_matplotlib
import os

# 디렉터리 경로 설정
base_dir = r"e:\fastcampus\icb6\p2\koreatravel"
data_nat_path = os.path.join(base_dir, "data", "raw", "visitor_by_nationality.csv")
data_trans_path = os.path.join(base_dir, "data", "raw", "visitor_by_transport.csv")
img_dir = os.path.join(base_dir, "images")

# 데이터 로드
df_nat = pd.read_csv(data_nat_path)
df_trans = pd.read_csv(data_trans_path)

print("="*50)
print("1. 데이터 샘플 출력")
print("="*50)
print("[visitor_by_nationality] 상위 5개행")
print(df_nat.head())
print("\n[visitor_by_nationality] 하위 5개행")
print(df_nat.tail())
print("\n[visitor_by_transport] 상위 5개행")
print(df_trans.head())
print("\n[visitor_by_transport] 하위 5개행")
print(df_trans.tail())

print("\n" + "="*50)
print("2. 데이터 기본 정보 (info, 크기, 중복)")
print("="*50)
print("[visitor_by_nationality.csv Info]")
df_nat.info()
print(f"\n- 데이터 크기(행, 열): {df_nat.shape}")
print(f"- 중복 데이터 수: {df_nat.duplicated().sum()}")

print("\n[visitor_by_transport.csv Info]")
df_trans.info()
print(f"\n- 데이터 크기(행, 열): {df_trans.shape}")
print(f"- 중복 데이터 수: {df_trans.duplicated().sum()}")

print("\n" + "="*50)
print("3. 기초 기술통계량 (범주형, 수치형)")
print("="*50)
print("[visitor_by_nationality] 수치형:")
print(df_nat.describe())
print("\n[visitor_by_nationality] 범주형:")
print(df_nat.describe(include=['object']))

print("\n[visitor_by_transport] 수치형:")
print(df_trans.describe())
print("\n[visitor_by_transport] 범주형:")
print(df_trans.describe(include=['object']))

# 데이터 타입 변환 전처리
df_trans['기준연월'] = pd.to_datetime(df_trans['기준연월'])
df_trans = df_trans.sort_values('기준연월')
df_nat['기준연월'] = pd.to_datetime(df_nat['기준연월'])

print("\n" + "="*50)
print("4. 데이터 시각화 교차표 및 피봇연산 내역")
print("="*50)

# 시각화 1. 성별 전체 방문객 (Bar) - 일변량
print("\n[그래프 1 해당 표] 성별 전체 인원수 합계")
ct1 = df_nat.groupby('성별')['인원수'].sum()
print(ct1)
plt.figure(figsize=(7,5))
ct1.plot(kind='bar', color=['#87CEFA', '#FA8072', '#98FB98'])
plt.title('성별 기준 전체 관광객 인원수 분포')
plt.xlabel('성별')
plt.ylabel('유입 인원수')
plt.xticks(rotation=0)
plt.tight_layout()
plt.savefig(os.path.join(img_dir, '01_gender_total.png'))
plt.close()

# 시각화 2. 연령별 인원 빈도수 상위 30 (Bar) - 일변량
print("\n[그래프 2 해당 표] 연령별 인원합계 (상위 30)")
ct2 = df_nat.groupby('연령별')['인원수'].sum().sort_values(ascending=False).head(30)
print(ct2)
plt.figure(figsize=(8,5))
ct2.plot(kind='bar', color='#FFA07A')
plt.title('연령별 관광객 유입 순위 (상위 30개 그룹)')
plt.ylabel('인원수')
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig(os.path.join(img_dir, '02_age_total.png'))
plt.close()

# 시각화 3. 방문목적별 인원수 (Bar) - 일변량
print("\n[그래프 3 해당 표] 방문목적별 인원수")
ct3 = df_nat.groupby('목적별')['인원수'].sum().sort_values(ascending=False)
print(ct3)
plt.figure(figsize=(8,5))
ct3.plot(kind='bar', color='#DDA0DD')
plt.title('방문 목적별 인원수 차이 비교')
plt.ylabel('인원수')
plt.xticks(rotation=0)
plt.tight_layout()
plt.savefig(os.path.join(img_dir, '03_purpose_total.png'))
plt.close()

# 시각화 4. 공항/항구별 누적 합계 (Bar) - 다변량 합산
ports = [col for col in df_trans.columns if col != '기준연월']
print("\n[그래프 4 해당 표] 각 공항 및 항구별 누적 유입객")
ct4 = df_trans[ports].sum().sort_values(ascending=False)
print(ct4)
plt.figure(figsize=(10,6))
ct4.plot(kind='bar', color='#20B2AA')
plt.title('공항 및 항구별 누적 이용 방문객 수')
plt.ylabel('누적 이용자 수')
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig(os.path.join(img_dir, '04_transport_total.png'))
plt.close()

# 시각화 5. 기준연월별 외래관광객 입국 추세 (Line) - 이변량 (시계열)
print("\n[그래프 5 해당 표] 기준연월별 전체 방문객 누적")
ct5 = df_nat.groupby('기준연월')['인원수'].sum().sort_index()
print(ct5)
plt.figure(figsize=(10, 5))
ct5.plot(kind='line', marker='o', color='#DC143C')
plt.title('기준연월별 외래관광객 입국 총 인원 추이')
plt.xlabel('기준연월')
plt.ylabel('인원수')
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()
plt.savefig(os.path.join(img_dir, '05_monthly_trend.png'))
plt.close()

# 시각화 6. 연령별 및 성별 교차 인원수 (Stacked Bar) - 이변량
print("\n[그래프 6 해당 표] 연령별-성별 교차표 (Pivot Table)")
ct6 = df_nat.pivot_table(index='연령별', columns='성별', values='인원수', aggfunc='sum').fillna(0)
print(ct6)
plt.figure(figsize=(10, 6))
ct6.plot(kind='bar', stacked=True, ax=plt.gca(), cmap='Pastel1')
plt.title('연령별 및 성별 입국 인원수 점유 비중')
plt.ylabel('인원수 누적')
plt.xticks(rotation=45)
plt.legend(title='성별')
plt.tight_layout()
plt.savefig(os.path.join(img_dir, '06_age_gender_stacked.png'))
plt.close()

# 시각화 7. 방문목적별 연령별 히트맵 비중 (Heatmap using imshow) - 다변량
print("\n[그래프 7 해당 표] 방문목적별-연령별 교차 합계표")
ct7 = df_nat.pivot_table(index='목적별', columns='연령별', values='인원수', aggfunc='sum').fillna(0)
print(ct7)
plt.figure(figsize=(10, 6))
plt.imshow(ct7.values, cmap='YlGnBu', aspect='auto')
plt.title('방문목적 및 연령대별 방문객 분산 밀집도 (Heatmap)')
plt.colorbar(label='합계 인원수')
plt.xticks(ticks=range(len(ct7.columns)), labels=ct7.columns, rotation=45)
plt.yticks(ticks=range(len(ct7.index)), labels=ct7.index)
plt.tight_layout()
plt.savefig(os.path.join(img_dir, '07_purpose_age_heatmap.png'))
plt.close()

# 시각화 8. 주요 공항 탑3 월별 비례 추이 (Line) - 다변량
print("\n[그래프 8 해당 표] 주요 상위 3개 공항(인천/김포/김해) 월별 이용객")
ct8 = df_trans.set_index('기준연월')[['인천공항', '김포공항', '김해공항']]
print(ct8)
plt.figure(figsize=(10, 5))
ct8.plot(kind='line', marker='x', ax=plt.gca(), linewidth=2)
plt.title('TOP 3 주요 공항 (인천, 김포, 김해) 연월별 입국 추세')
plt.xlabel('기준연월')
plt.ylabel('이용객 수')
plt.grid(True, linestyle=':')
plt.legend(title='공항명')
plt.tight_layout()
plt.savefig(os.path.join(img_dir, '08_top3_airports_trend.png'))
plt.close()

# 시각화 9. 연월별 방문 목적 추이 분석 (Multi-line) - 이변량
print("\n[그래프 9 해당 표] 연월별 방문목적 교차 빈도 (Line Trend)")
ct9 = df_nat.pivot_table(index='기준연월', columns='목적별', values='인원수', aggfunc='sum').fillna(0)
print(ct9)
plt.figure(figsize=(12, 6))
ct9.plot(kind='line', marker='s', ax=plt.gca())
plt.title('방문 연월에 따른 목적별 외국인 입국 인원 상세 추이')
plt.xlabel('기준연월')
plt.ylabel('인원수')
plt.grid(True, alpha=0.5)
plt.legend(title='방문 목적')
plt.tight_layout()
plt.savefig(os.path.join(img_dir, '09_monthly_purpose_trend.png'))
plt.close()

# 시각화 10. 전체 교통수단 점유율 (Pie) - 일변량
print("\n[그래프 10 해당 표] 상위 5개 수단 및 기타 병합 비중")
ct10 = df_trans[ports].sum().sort_values(ascending=False)
top_5 = ct10.head(5)
others = pd.Series({'기타 공항/항구 합산': ct10.iloc[5:].sum()})
ct10_pie = pd.concat([top_5, others])
print(ct10_pie)
plt.figure(figsize=(8,8))
ct10_pie.plot(kind='pie', autopct='%1.1f%%', startangle=140, cmap='Set2', textprops={'fontsize': 11})
plt.title('국내 주요 입국 공항 및 항구별 총 이용자 비중')
plt.ylabel('')
plt.tight_layout()
plt.savefig(os.path.join(img_dir, '10_transport_pie.png'))
plt.close()

print("\n" + "="*50)
print("EDA 스크립트 실행 완료. 총 10개의 그래프가 정상적으로 생성 및 저장되었습니다.")
print("="*50)
